/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OAuth 시작 (Authorization Code + PKCE)
         * @description OAuth 인가 플로우를 시작합니다.
         *
         *     클라이언트 IP, User-Agent, deviceId 등을 기반으로
         *     PKCE 코드 챌린지 및 state를 생성하여 Auth Server로 이동할 URL을 반환합니다.
         */
        get: operations["StartOAuthController_startOauth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 사용자 정보 조회
         * @description 현재 세션을 기반으로 사용자 정보를 조회합니다.
         *
         *     ※ 주의
         *     - 세션 검증(로그인 여부) → UserSessionGuard에서 처리
         *     - 세션 갱신 또는 부가 처리 → MeSessionInterceptor에서 처리
         *     - 컨트롤러는 실제 사용자 정보를 JSON 형태로 반환합니다.
         */
        get: operations["MeController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 세션을 제거하고, 인터셉터를 통해 브라우저의 세션 쿠키(session_id)를 삭제합니다.
         *
         *     응답 자체는 JSON을 반환하지만, 실제 쿠키 삭제는 LogoutCookieClearInterceptor에서 처리됩니다.
         */
        post: operations["LogoutController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseDto: {
            /**
             * @description 요청 성공 여부
             * @example true
             */
            success: boolean;
            /**
             * @description 수행된 작업(operation) 이름
             * @example get_users
             */
            operation: string;
            /**
             * @description 사용자에게 보여질 메시지
             * @example 조회 성공
             */
            message: string;
            /** @description API 실제 데이터 */
            data: Record<string, never> | null;
        };
        StartOAuthResponseDto: {
            /**
             * @description 클라이언트가 이동해야 할 OAuth 인가 엔드포인트 URL (PKCE 포함)
             * @example http://localhost:3001/oauth/authorize?client_id=partner-center&redirect_uri=http://localhost:3002/oauth/callback&state=8c4f0e20&code_challenge=vsh1d9k2&code_challenge_method=S256
             */
            authorizeUrl: string;
        };
        StartOAuthRequestDto: {
            /**
             * @description 디바이스 고유 식별자(브라우저 또는 앱 단위). 클라이언트가 생성해 전달합니다.
             * @example c6e54331-47c6-4bf5-8e1a-1b2cafb0df91
             */
            deviceId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    StartOAuthController_startOauth: {
        parameters: {
            query: {
                /** @description 디바이스 고유 식별자(브라우저 또는 앱 단위). 클라이언트가 생성해 전달합니다. */
                deviceId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OAuth 시작 URL 및 state 정보가 정상적으로 반환됩니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseDto"] & {
                        data?: components["schemas"]["StartOAuthResponseDto"];
                    };
                };
            };
        };
    };
    MeController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 정상적으로 사용자 정보를 반환합니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 세션이 없거나 만료된 경우 (Unauthorized) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LogoutController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 정상적으로 로그아웃되었습니다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
